import * as lucide from 'lucide-vue-next'

const icons = {
  'arrow-big-left': lucide.ArrowBigLeft,
  'bone': lucide.Bone,
  'bookmark': lucide.Bookmark,
  'check': lucide.Check,
  'chevrons-left': lucide.ChevronsLeft,
  'chevrons-right': lucide.ChevronsRight,
  'chevron-left': lucide.ChevronLeft,
  'chevron-right': lucide.ChevronRight,
  'chevron-down': lucide.ChevronDown,
  'chevron-up': lucide.ChevronUp,
  'cloud': lucide.Cloud,
  'cloud-drizzle': lucide.CloudDrizzle,
  'cloud-rain': lucide.CloudRain,
  'cloud-lightning': lucide.CloudLightning,
  'cloud-snow': lucide.CloudSnow,
  'code': lucide.Code,
  'code-xml': lucide.CodeXml,
  'cog': lucide.Cog,
  'component': lucide.Component,
  'copy': lucide.Copy,
  'crop': lucide.Crop,
  'download': lucide.Download,
  'ellipsis': lucide.Ellipsis,
  'edit': lucide.Edit,
  'external-link': lucide.ExternalLink,
  'file': lucide.File,
  'filter': lucide.Filter,
  'file-input': lucide.FileInput,
  'file-up': lucide.FileUp,
  'file-search': lucide.FileSearch,
  'file-x': lucide.FileX,
  'grid': lucide.Grid,
  'grid-2x2': lucide.Grid2x2,
  'key-round': lucide.KeyRound,
  'info': lucide.Info,
  'image': lucide.Image,
  'link-2': lucide.Link2,
  'list': lucide.List,
  'list-plus': lucide.ListPlus,
  'loader': lucide.Loader,
  'log-out': lucide.LogOut,
  'menu': lucide.Menu,
  'more-horizontal': lucide.MoreHorizontal,
  'plus': lucide.Plus,
  'search': lucide.Search,
  'share-2': lucide.Share2,
  'space': lucide.Space,
  'square-check-big': lucide.SquareCheckBig,
  'sun': lucide.Sun,
  'tag': lucide.Tag,
  'toy-brick': lucide.ToyBrick,
  'trash-2': lucide.Trash2,
  'undo-2': lucide.Undo2,
  'upload': lucide.Upload,
  'user': lucide.User,
  'user-round': lucide.UserRound,
  'user-round-cog': lucide.UserRoundCog,
  'user-round-plus': lucide.UserRoundPlus,
  'youtube': lucide.Youtube,
  'x': lucide.X,
}

export function iconRandomPick()
{
  const iconNames = Object.keys(icons)
  return iconNames[Math.floor(Math.random() * iconNames.length)]
}

export default icons
